name: bookly
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz_plus: ^0.3.0
  dio: ^5.9.2
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  font_awesome_flutter: ^11.0.0
  
  go_router: ^17.3.0
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf